### ISSUE TITLE
Confirmation

### ISSUE THREAD

**Issue by timea-techgirl** [venerjoel99/TarProject#3]
Hello,
Thank you so much for this amazing program. I tried both the cleaners, yours and BuildingAtom's. His program crashed but yours worked for me. I was able to restore my corrupted backup even though it ended in a bootloop.

When I use your program, after it finishes processing the file, the command window closes. There is no log or confirmation.

Can you please add a pause command or "File was cleaned successfully. Press any key to exit" so that we can know that it was successful? Because some apps that crash just close themselves.

Thanks a lot!

**Comment by venerjoel99** [comment]
I have made sure that both executables do not exit suddenly right after cleaning tar files.  The user will now have to enter in any non-empty string to properly exit the application.

**Comment by timea-techgirl** [comment]
Thanks, it works fine now.
The "BigTarCleaner" gives error regarding VCRuntime and some dll. What are the requirements?

**Comment by venerjoel99** [comment]
I believe the requirement is Microsoft Visual C++ Redistributable for Visual Studio 2017. 
Here is the link: https://go.microsoft.com/fwlink/?LinkId=746572

**Comment by timea-techgirl** [comment]
Thanks. Please update the readme to include this requirement for the BigTarCleaner. :)
